-- ====================================================
-- ESQUEMA SQL PARA REVISTAUTO EN SUPABASE
-- Copia y pega todo este código en el SQL Editor de Supabase
-- ====================================================

-- 1. Crear extensión para gen_random_uuid si no existe
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tabla principal de Anuncios (Listings)
CREATE TABLE IF NOT EXISTS public.listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    state TEXT,
    city TEXT NOT NULL,
    color TEXT,
    transmission TEXT DEFAULT 'Automática',
    mileage INT DEFAULT 0,
    description TEXT,
    seller_name TEXT,
    seller_phone TEXT,
    seller_whatsapp TEXT,
    images TEXT[] DEFAULT '{}',
    status TEXT DEFAULT 'pendiente', -- 'pendiente', 'autorizado', 'rechazado', 'pausado', 'destacado'
    views INT DEFAULT 0,
    notes JSONB DEFAULT '[]'::jsonb,
    payments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 COMANDOS PARA ACTUALIZAR LA TABLA EXISTENTE CON NUEVAS COLUMNAS (EJECÚTALOS SI TE FALTA ALGUNA)
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS engine TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS ac TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS legal TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS trim TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS publisher_id TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS last_renewed_month TEXT;
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS payment_status TEXT;

-- 2.6 COMANDO PARA CAMBIAR MILEAGE A TEXTO (EJECÚTALO PARA ARREGLAR EL ERROR DE "invalid input syntax for type integer")
ALTER TABLE public.listings ALTER COLUMN mileage TYPE TEXT USING mileage::TEXT;
-- 3. Habilitar la búsqueda rápida e índices
CREATE INDEX IF NOT EXISTS idx_listings_status ON public.listings(status);
CREATE INDEX IF NOT EXISTS idx_listings_make ON public.listings(make);
CREATE INDEX IF NOT EXISTS idx_listings_city ON public.listings(city);
CREATE INDEX IF NOT EXISTS idx_listings_state ON public.listings(state);

-- 4. Tabla de Catálogo (Marcas, Modelos, Colores, Regiones)
CREATE TABLE IF NOT EXISTS public.catalog (
    id INT PRIMARY KEY DEFAULT 1,
    data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- NUEVAS TABLAS PARA LA MIGRACIÓN COMPLETA
-- 4.1 Tabla de Configuraciones Generales (Settings)
CREATE TABLE IF NOT EXISTS public.settings (
    id INT PRIMARY KEY DEFAULT 1,
    monthlyPrice NUMERIC(12,2) DEFAULT 500,
    mercadoPagoEnabled BOOLEAN DEFAULT false,
    mpPublicKey TEXT,
    mpAccessToken TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4.2 Tabla de Ubicaciones Activas (Locations)
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state TEXT NOT NULL,
    cities JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 4.3 Tabla de Usuarios Administradores (Admin Users)
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'empleado',
    allowedStates JSONB DEFAULT '[]'::jsonb,
    allowedCities JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insertar admin por defecto
INSERT INTO public.admin_users (username, password, role) 
VALUES ('admin', 'admin', 'admin') ON CONFLICT DO NOTHING;

-- 5. Habilitar Políticas de Acceso Público (Lectura y Escritura para la App)
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Políticas para Listings (Permitir lectura y creación a todos)
CREATE POLICY "Permitir lectura pública de anuncios" ON public.listings FOR SELECT USING (true);
CREATE POLICY "Permitir insertar anuncios" ON public.listings FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualizar anuncios" ON public.listings FOR UPDATE USING (true);
CREATE POLICY "Permitir eliminar anuncios" ON public.listings FOR DELETE USING (true);

-- Políticas para Catálogo y Locations
CREATE POLICY "Permitir lectura pública de catálogo" ON public.catalog FOR SELECT USING (true);
CREATE POLICY "Permitir actualización de catálogo" ON public.catalog FOR ALL USING (true);

CREATE POLICY "Permitir lectura pública de ubicaciones" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Permitir actualización de ubicaciones" ON public.locations FOR ALL USING (true);

-- Políticas para Settings y Admins (Públicas en este momento, considerar ajustar seguridad en producción)
CREATE POLICY "Permitir lectura pública de settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Permitir actualización de settings" ON public.settings FOR ALL USING (true);

CREATE POLICY "Permitir acceso a admin_users" ON public.admin_users FOR ALL USING (true);

-- 6. Configurar Bucket de Almacenamiento de Fotos ('car-images')
INSERT INTO storage.buckets (id, name, public) 
VALUES ('car-images', 'car-images', true)
ON CONFLICT (id) DO NOTHING;

-- Permisos públicos para el bucket car-images
CREATE POLICY "Acceso público a fotos de autos" ON storage.objects FOR SELECT USING (bucket_id = 'car-images');
CREATE POLICY "Permitir subir fotos de autos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'car-images');
CREATE POLICY "Permitir borrar fotos de autos" ON storage.objects FOR DELETE USING (bucket_id = 'car-images');

-- 7. Tabla de Visitas Diarias (Para analíticas reales)
CREATE TABLE IF NOT EXISTS public.daily_visits (
    date DATE PRIMARY KEY,
    visits INT DEFAULT 0
);

ALTER TABLE public.daily_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica de visitas" ON public.daily_visits FOR SELECT USING (true);
CREATE POLICY "Permitir insercion publica de visitas" ON public.daily_visits FOR ALL USING (true);

-- Función segura para incrementar vistas y visitas globales al mismo tiempo
CREATE OR REPLACE FUNCTION increment_visit(listing_id BIGINT, visit_date DATE)
RETURNS void AS $$
BEGIN
    -- Incrementar en la tabla de visitas globales
    INSERT INTO public.daily_visits (date, visits)
    VALUES (visit_date, 1)
    ON CONFLICT (date)
    DO UPDATE SET visits = public.daily_visits.visits + 1;

    -- Incrementar en la tabla listings
    UPDATE public.listings 
    SET views = COALESCE(views, 0) + 1 
    WHERE id = listing_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
